---
title: "py-exceptiongroup"
layout: cache
categories: [package, v2025.07.0]
meta: {"compilers": ["none"], "num_specs": 1, "num_specs_by_stack": {"hep": 1, "root": 1}, "oss": ["ubuntu22.04"], "platforms": ["linux"], "stacks": ["hep", "root"], "targets": ["x86_64_v3"], "versions": ["1.1.1"]}
spec_details: [{"compiler": "none", "hash": "qydm6da6ktynelsvrdg27m4hqqasvbxt", "os": "ubuntu22.04", "platform": "linux", "size": "-", "stacks": ["hep", "root"], "target": "x86_64_v3", "variants": ["build_system=python_pip"], "versions": ["1.1.1"]}]
---